// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OAProjects.Data.OAIdentity.Context;

#nullable disable

namespace OAProjects.Data.OAIdentity.Migrations
{
    [DbContext(typeof(OAIdentityDbContext))]
    [Migration("20260225182901_0.001")]
    partial class _0001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OAProjects.Data.OAIdentity.Entities.OA_ID_XREF", b =>
                {
                    b.Property<int>("ID_XREF_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_XREF_ID"));

                    b.Property<int>("NEW_ID")
                        .HasColumnType("int");

                    b.Property<int>("OLD_ID")
                        .HasColumnType("int");

                    b.Property<int>("TABLE_ID")
                        .HasColumnType("int");

                    b.HasKey("ID_XREF_ID");

                    b.ToTable("OA_ID_XREF");
                });

            modelBuilder.Entity("OAProjects.Data.OAIdentity.Entities.OA_USER", b =>
                {
                    b.Property<int>("USER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("USER_ID"));

                    b.Property<DateTime>("DATE_ADDED")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FIRST_NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LAST_NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("USER_NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("USER_ID");

                    b.ToTable("OA_USER");
                });

            modelBuilder.Entity("OAProjects.Data.OAIdentity.Entities.OA_USER_TOKEN", b =>
                {
                    b.Property<int>("USER_TOKEN_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("USER_TOKEN_ID"));

                    b.Property<DateTime>("EXPIRY_DATE_UTC")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EXPIRY_TIME")
                        .HasColumnType("int");

                    b.Property<int>("ISSUED_AT")
                        .HasColumnType("int");

                    b.Property<DateTime>("ISSUED_AT_DATE_UTC")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TOKEN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("USER_ID")
                        .HasColumnType("int");

                    b.HasKey("USER_TOKEN_ID");

                    b.ToTable("OA_USER_TOKEN");
                });
#pragma warning restore 612, 618
        }
    }
}
