DELETE FROM FT_TRANSACTION_OFFSET;
DELETE FROM FT_TRANSACTION;
DELETE FROM FT_ACCOUNT;
DELETE FROM FT_ID_XREF;

ALTER TABLE FT_TRANSACTION_OFFSET AUTO_INCREMENT = 1000;
ALTER TABLE FT_TRANSACTION AUTO_INCREMENT = 1000;
ALTER TABLE FT_ACCOUNT AUTO_INCREMENT = 1000;
ALTER TABLE FT_ID_XREF AUTO_INCREMENT = 1000;