name: OAProjects-API Deployment

on:
  push:
    branches: [ main ]
    
defaults:
  run:
    working-directory: OAProjects.API

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET  
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: API Publish
      run: dotnet publish ./OAProjects.API/OAProjects.API.csproj -c Release --output ./Release-API

    - name: Batch Publish
      run: dotnet publish ./OAProjects.Batch/OAProjects.Batch.csproj -c Release --output ./Release-Batch    
 
    - name: API App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: ./OAProjects.API/Release-API/appsettings.json
      env:
        ConnectionStrings.ShowLoggerConnection: ${{ secrets.SHOW_LOGGER_DB }}
        ConnectionStrings.FinanceTrackerConnection: ${{ secrets.FINANCE_TRACKER_DB }}
        ConnectionStrings.OAIdentityConnection: ${{ secrets.OA_IDENTITY_DB }}
        ListeningPort: ${{ secrets.LISTENING_PORT }}
        Auth0.Domain: ${{ secrets.AUTH0_DOMAIN }}
        Auth0.Audience: ${{ secrets.AUTH0_AUDIENCE }}
        Auth0.Url: ${{ secrets.AUTH0_URL }}
        Auth0.Auth0ClientId: ${{ secrets.AUTH0_AUTH0CLIENTID }}
        Auth0.Auth0ClientSecret: ${{ secrets.AUTH0_CLIENTSECRET }}
        Auth0.Auth0Audience: ${{ secrets.AUTH0_AUTH0AUDIENCE }}
        Auth0.AUth0GrantType: ${{ secrets.AUTH0_GRANTTYPE }}
        Auth0.Auth0Scopes: ${{ secrets.AUT0_SCOPES }}
        Apis.TMDbAPIKey: ${{ secrets.APIS_TMDBAPIKEY }}
        ShowLoggerSettings.LatestReleaseDate: ${{ env.ReleaseDate }}

    - name: Batch App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: ./OAProjects.API/Release-Batch/appsettings.json
      env:
        Auth0API.Auth0Url: ${{ secrets.BATCH_AUTH0API_AUTH0URL }}
        Auth0API.Auth0ClientId: ${{ secrets.BATCH_AUTH0API_AUTH0CLIENTID }}
        Auth0API.Auth0ClientSecret: ${{ secrets.BATCH_AUTH0API_AUTH0CLIENTSECRET }}
        Auth0API.Auth0Audience: ${{ secrets.BATCH_AUTH0API_AUTH0AUDIENCE }}
        Auth0API.Auth0GrantType: ${{ secrets.BATCH_AUTH0API_AUTH0GRANTTYPE }}
        Auth0API.Auth0Scopes: ${{ secrets.BATCH_AUTH0API_AUTH0SCOPES }}
        OAProjectsAPI: ${{ secrets.BATCH_OAPROJECTSAPI }}
        LogFolderPath: ${{ secrets.BATCH_LOGFOLDERPATH }}   
        
    - name: API SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: '${{ secrets.SSH_USER }}'
        server: '${{ secrets.SSH_IP_ADDRESS }}'
        port: 22
        ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
        local_path: './OAProjects.API/Release-API/*'
        remote_path: '/oaprojects/oaprojects-api'

    - name: Restart OAProjects-API
      uses: appleboy/ssh-action@v1.0.3
      with:
        username: ${{ secrets.SSH_USER }}
        host: ${{ secrets.SSH_IP_ADDRESS }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          ${{ secrets.SSH_RESTART_OAPROJECTS }}        

    - name: Batch SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: '${{ secrets.SSH_USER }}'
        server: '${{ secrets.SSH_IP_ADDRESS }}'
        port: 22
        ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
        local_path: './OAProjects.API/Release-Batch/*'
        remote_path: '/oaprojects/oaprojects-batch'        
  
